In [18]:
import pandas as pd
import numpy as np
import datetime as dt

import matplotlib.pyplot as plt
import seaborn as sns

from droughts_modelling.data import DataFunctions
from sklearn.feature_selection import SelectKBest, f_classif, chi2

pd.options.display.max_columns = 99

In [10]:
df = DataFunctions().light_weekly_aggregate()

In [11]:
df.head()

,fips_,year_,week_num_,PRECTOT_mean,PS_mean,QV2M_mean,T2M_mean,T2MDEW_mean,T2MWET_mean,T2M_MAX_mean,T2M_MIN_mean,T2M_RANGE_mean,TS_mean,WS10M_mean,WS10M_MAX_mean,WS10M_MIN_mean,WS10M_RANGE_mean,WS50M_mean,WS50M_MAX_mean,WS50M_MIN_mean,WS50M_RANGE_mean,score_max
0,1001,2000,1,5.261429,100.702857,6.491429,9.878571,5.648571,5.674286,16.345714,3.647143,12.698571,9.397143,2.630000,3.722857,1.520000,2.201429,5.044286,6.934286,2.815714,4.120000,1.0
1,1001,2000,2,3.554286,101.100000,6.104286,9.662857,5.527143,5.552857,16.751429,2.928571,13.825714,9.431429,2.472857,3.585714,1.568571,2.018571,5.142857,7.162857,2.968571,4.192857,2.0
2,1001,2000,3,4.017143,100.348571,6.090000,8.270000,4.834286,4.890000,13.738571,2.795714,10.941429,8.194286,2.507143,3.574286,1.461429,2.110000,4.702857,6.682857,2.997143,3.685714,2.0
3,1001,2000,4,3.742857,100.755714,3.072857,0.737143,-3.367143,-3.265714,5.570000,-3.320000,8.890000,0.817143,2.774286,3.908571,1.664286,2.248571,4.928571,6.727143,3.244286,3.480000,2.0
4,1001,2000,5,0.000000,101.012857,3.142857,2.501429,-2.685714,-2.627143,10.460000,-3.842857,14.301429,2.021429,2.211429,3.161429,1.225714,1.934286,4.125714,5.971429,2.045714,3.927143,1.0

In [39]:
df['year_'].dtypes

dtype('int64')

In [42]:
df[df['score_max'].isna()]

,fips_,year_,week_num_,PRECTOT_mean,PS_mean,QV2M_mean,T2M_mean,T2MDEW_mean,T2MWET_mean,T2M_MAX_mean,T2M_MIN_mean,T2M_RANGE_mean,TS_mean,WS10M_mean,WS10M_MAX_mean,WS10M_MIN_mean,WS10M_RANGE_mean,WS50M_mean,WS50M_MAX_mean,WS50M_MIN_mean,WS50M_RANGE_mean,score_max
887,1003,1999,52,0.535,101.600,11.800,17.815,16.775,16.775,22.265,14.850,7.415,17.630,2.615,3.365,2.010,1.360,5.055,6.125,3.830,2.300,NaN
1775,1005,1999,52,0.120,100.865,9.790,15.305,13.750,13.750,22.465,10.250,12.215,15.195,2.060,2.660,1.530,1.130,4.510,5.585,2.525,3.055,NaN
2663,1007,1999,52,0.305,100.400,9.710,15.125,13.575,13.575,21.240,10.960,10.280,15.110,2.120,2.905,1.565,1.340,5.045,6.055,3.410,2.640,NaN
3551,1009,1999,52,0.370,99.650,9.555,14.880,13.240,13.245,20.535,10.650,9.880,14.845,2.385,3.290,1.740,1.550,5.380,6.160,4.085,2.075,NaN
4439,1011,1999,52,0.110,100.575,9.875,15.430,13.845,13.845,22.020,11.100,10.920,15.370,2.005,2.570,1.405,1.165,4.640,5.950,2.805,3.145,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2755463,56035,1999,52,0.250,74.810,1.755,-11.020,-13.210,-13.140,-5.585,-16.175,10.590,-12.390,3.335,5.215,1.805,3.410,5.035,6.545,3.025,3.520,NaN
2756351,56037,1999,52,0.235,77.750,1.980,-7.430,-11.370,-11.230,-2.375,-11.805,9.430,-7.940,5.080,7.685,3.005,4.680,7.195,9.855,4.400,5.460,NaN
2757239,56039,1999,52,1.520,75.350,1.750,-12.875,-13.210,-13.205,-8.900,-18.135,9.240,-13.750,2.180,2.750,1.535,1.215,4.085,5.075,2.950,2.130,NaN
2758127,56041,1999,52,0.970,75.345,1.860,-9.665,-12.450,-12.365,-5.810,-13.765,7.955,-10.580,3.870,5.735,2.690,3.045,5.900,7.520,4.495,3.030,NaN
2759015,56043,1999,52,0.160,82.110,2.150,-3.785,-9.760,-9.620,1.100,-7.695,8.795,-4.985,2.955,5.400,1.435,3.965,4.435,7.740,2.185,5.555,NaN

In [48]:
def k_best(df):
    y = round(df['score_max'])
    X = df.drop(columns=['fips_', 'year_', 'week_num_', 'score_max'])
    
    k_best_f = SelectKBest(f_classif, k=10).fit(X, y)
    df_scores = pd.DataFrame({'features': X.columns, 'ANOVA F-value': k_best_f.scores_, 'pValue': k_best_f.pvalues_ })

    return df_scores.sort_values('ANOVA F-value', ascending=False).reset_index()

In [49]:
k_best(df.dropna())

    index          features  ANOVA F-value         pValue
0       8    T2M_RANGE_mean   42939.660402   0.000000e+00
1       1           PS_mean   20921.723797   0.000000e+00
2       6      T2M_MAX_mean    9304.746500   0.000000e+00
3      13  WS10M_RANGE_mean    6030.908852   0.000000e+00
4       0      PRECTOT_mean    5982.366774   0.000000e+00
5       9           TS_mean    5596.430819   0.000000e+00
6       3          T2M_mean    4849.891364   0.000000e+00
7      17  WS50M_RANGE_mean    4569.074706   0.000000e+00
8       7      T2M_MIN_mean    2664.316644   0.000000e+00
9       4       T2MDEW_mean    2657.948573   0.000000e+00
10      5       T2MWET_mean    2602.284426   0.000000e+00
11     11    WS10M_MAX_mean    2531.072508   0.000000e+00
12      2         QV2M_mean    2109.909454   0.000000e+00
13     16    WS50M_MIN_mean    1106.461148   0.000000e+00
14     10        WS10M_mean    1026.388412   0.000000e+00
15     15    WS50M_MAX_mean     806.133325   0.000000e+00
16     12    WS10M_MIN_mean     218.151962  1.491800e-233
17     14        WS50M_mean     202.019565  4.291735e-216